import 'package:flutter/material.dart';

  class Carros {
    final String nome;
    final String modelo;
    final String preco;
    final double avaliacao;
    final String image;
    final String descricao;
    final List<Color> cores;
    final List<String> itensAdicionais;

    Carros({
      required this.nome,
      required this.modelo,
      required this.preco,
      required this.avaliacao,
      required this.image,
      required this.descricao,
      required this.cores,
      required this.itensAdicionais,
    });
  }

  List<Carros> allCarros = [
  Carros(
    nome: 'Prius',
    modelo: '2021',
    preco: 'R\$80.000,00',
    avaliacao: 4.5,
    image: 'assets/prius.png',
    descricao: 'O Toyota Prius 2021 é a mais recente versão do pioneiro carro híbrido, combinando um motor a combustão eficiente com um motor elétrico. Oferece uma condução suave e silenciosa, além de uma economia de combustível impressionante. O design aerodinâmico e moderno é complementado por uma cabine espaçosa e equipada com tecnologia de ponta.',
    cores: [Colors.blue, Colors.black, Colors.white],
    itensAdicionais: [
      'Detecção de ponto cego (BSD)',
      'Sistema de freio motorizado inteligente',
      'Monitoramento da fadiga do motorista (DFM)',
      'Reconhecimento de sinais de trânsito (TSR)',
      'Trava manual de segurança para crianças',
      'Ar-condicionado dual zone',
      'Conexão Bluetooth para smartphones',
      'Faróis LED automáticos',
    ],
  ),
  Carros(
    nome: 'Civic Hybrid',
    modelo: '2022',
    preco: 'R\$70.000,00',
    avaliacao: 4.3,
    image: 'assets/CivicHybrid.png',
    descricao: 'O Honda Civic Hybrid 2022 oferece desempenho, eficiência e estilo. Combinando um design esportivo com um motor híbrido avançado, ele proporciona economia de combustível excepcional e conforto premium. Ideal para quem busca sustentabilidade sem abrir mão de potência.',
    cores: [Colors.grey, Colors.black],
    itensAdicionais: [
      'Controle adaptativo de velocidade',
      'Sistema de frenagem automática',
      'Câmera traseira com guias dinâmicas',
      'Assistência de permanência em faixa',
      'Banco do motorista ajustável eletricamente',
      'Carregador sem fio para dispositivos móveis',
      'Sistema de som premium',
      'Sensores de estacionamento dianteiros e traseiros',
    ],
  ),
  Carros(
    nome: 'Corolla Hybrid',
    modelo: '2023',
    preco: 'R\$65.000,00',
    avaliacao: 4.6,
    image: 'assets/Corolla.png',
    descricao: 'O Corolla Hybrid 2023 combina tradição e inovação em um sedã híbrido sofisticado. Com tecnologia de ponta, segurança avançada e desempenho eficiente, é perfeito para quem valoriza qualidade e sustentabilidade.',
    cores: [Colors.black, Colors.white],
    itensAdicionais: [
      'Sistema de pré-colisão',
      'Controle eletrônico de estabilidade',
      'Monitoramento de pressão dos pneus',
      'Faróis automáticos de LED',
      'Ar-condicionado automático dual zone',
      'Conexão USB em todas as fileiras',
      'Espelhos retrovisores rebatíveis eletricamente',
      'Central multimídia com tela sensível ao toque',
    ],
  ),
  Carros(
    nome: 'Insight',
    modelo: '2020',
    preco: 'R\$45.000,00',
    avaliacao: 4.2,
    image: 'assets/Insight.png',
    descricao: 'O Honda Insight 2020 é um sedã híbrido que une eficiência energética, conforto e tecnologia. Equipado com recursos avançados de assistência ao motorista, ele garante uma experiência de condução segura e agradável.',
    cores: [Colors.red, Colors.black, Colors.blue],
    itensAdicionais: [
      'Assistência de partida em subida',
      'Controle de tração e estabilidade',
      'Alerta de ponto cego',
      'Faróis de neblina',
      'Sistema de áudio premium com 6 alto-falantes',
      'Espelho retrovisor interno antiofuscante',
      'Sensores de chuva para os limpadores',
      'Bancos dianteiros aquecidos',
    ],
  ),
  Carros(
    nome: 'Auris Hybrid',
    modelo: '2018',
    preco: 'R\$55.000,00',
    avaliacao: 4.9,
    image: 'assets/Auris.png',
    descricao: 'O Auris Hybrid 2018 é um hatchback compacto que oferece uma combinação perfeita de eficiência, desempenho e estilo. Ideal para ambientes urbanos e viagens curtas, ele é uma escolha confiável para quem busca economia sem comprometer o conforto.',
    cores: [Colors.red, Colors.black, Colors.grey],
    itensAdicionais: [
      'Assistência de partida em subida',
      'Controle de tração e estabilidade',
      'Alerta de ponto cego',
      'Faróis de neblina',
      'Volante ajustável em altura e profundidade',
      'Computador de bordo multifuncional',
      'Sistema de navegação GPS integrado',
      'Conexão Wi-Fi integrada',
    ],
  ),
   Carros(
    nome: 'Tesla Model 3',
    modelo: '2023',
    preco: 'R\$200.000,00',
    avaliacao: 4.8,
    image: 'assets/tesla3.png',
    descricao: 'O Tesla Model 3 2023 é um sedã elétrico de alta performance que oferece tecnologia de ponta, direção autônoma e uma experiência de direção inigualável. Com excelente alcance e aceleração, é uma referência no segmento.',
    cores: [Colors.white, Colors.black, Colors.red],
    itensAdicionais: [
      'Piloto automático avançado',
      'Atualizações de software remotas',
      'Sistema de som premium',
      'Câmera de visão 360°',
      'Vidros com isolamento acústico',
      'Carregador rápido integrado',
      'Sistema de freios regenerativos',
      'Tela sensível ao toque de 15 polegadas',
    ],
  ),
  Carros(
    nome: 'Chevrolet Bolt EV',
    modelo: '2023',
    preco: 'R\$190.000,00',
    avaliacao: 4.6,
    image: 'assets/Bolt.png',
    descricao: 'O Chevrolet Bolt EV 2023 é um hatch elétrico compacto que oferece uma condução ágil, excelente alcance e tecnologia avançada. Ideal para deslocamentos urbanos e viagens curtas.',
    cores: [Colors.blue, Colors.grey, Colors.black],
    itensAdicionais: [
      'Sistema de carregamento rápido CCS',
      'Monitoramento de ponto cego',
      'Ar-condicionado automático',
      'Conexão Apple CarPlay e Android Auto',
      'Assistência de frenagem de emergência',
      'Tela central de 10,2 polegadas',
      'Bancos ajustáveis eletricamente',
      'Faróis automáticos em LED',
    ],
  ),
  Carros(
    nome: 'Hyundai Ioniq Electric',
    modelo: '2022',
    preco: 'R\$150.000,00',
    avaliacao: 4.4,
    image: 'assets/Ioniq.png',
    descricao: 'O Hyundai Ioniq Electric 2022 é um sedã compacto e eficiente que combina um design moderno com um motor totalmente elétrico, oferecendo uma experiência de direção sustentável e confortável.',
    cores: [Colors.grey, Colors.blue, Colors.white],
    itensAdicionais: [
      'Sistema de som Infinity',
      'Carregador rápido integrado',
      'Reconhecimento de pedestres',
      'Sistema de assistência em faixa',
      'Ar-condicionado dual zone',
      'Display digital de 7 polegadas',
      'Conexão sem fio para smartphones',
      'Retrovisores com aquecimento',
    ],
  ),
  Carros(
    nome: 'Nissan Leaf',
    modelo: '2023',
    preco: 'R\$180.000,00',
    avaliacao: 4.5,
    image: 'assets/Leaf.png',
    descricao: 'O Nissan Leaf 2023 é um dos pioneiros no segmento de carros elétricos, oferecendo confiabilidade, tecnologia de ponta e uma experiência de direção limpa e silenciosa.',
    cores: [Colors.white, Colors.black, Colors.green],
    itensAdicionais: [
      'Sistema e-Pedal',
      'ProPILOT Assist',
      'Câmera 360°',
      'Bancos dianteiros aquecidos',
      'Sistema de navegação inteligente',
      'Monitoramento de pressão dos pneus',
      'Carregamento rápido CHAdeMO',
      'Painel de instrumentos digital',
    ],
  ),
  Carros(
    nome: 'BMW i3',
    modelo: '2022',
    preco: 'R\$220.000,00',
    avaliacao: 4.7,
    image: 'assets/i3.png',
    descricao: 'O BMW i3 2022 combina luxo e sustentabilidade em um veículo compacto elétrico, oferecendo materiais ecológicos e um desempenho impressionante para a cidade.',
    cores: [Colors.black, Colors.white, Colors.orange],
    itensAdicionais: [
      'Sistema de regeneração de energia',
      'Interior com materiais recicláveis',
      'Assistência de estacionamento',
      'Sistema de som Harman Kardon',
      'Controle climático automático',
      'Portas traseiras no estilo "suicida"',
      'Faróis de LED adaptativos',
      'Painel de instrumentos em LCD',
    ],
  ),
];
